# Generated by Django 4.0.5 on 2022-06-12 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sticky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('text', models.CharField(max_length=1000)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickies.computer')),
            ],
        ),
    ]
