# Generated by Django 4.0.5 on 2022-06-12 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sticky',
            options={'verbose_name_plural': 'Stickies'},
        ),
        migrations.AlterField(
            model_name='sticky',
            name='window',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
