# Generated by Django 4.0.5 on 2022-06-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickies', '0002_alter_sticky_options_alter_sticky_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticky',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
