# Generated by Django 4.0.5 on 2022-06-12 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stickies', '0003_alter_sticky_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
